version: "3.9"

x-app: &app
  image: ${IMAGE_BACKEND}
  platform: linux/amd64
  env_file:
    - ./secrets/.env
  environment:
    SIDEKIQ_REDIS_URL: redis://redis:6379/0
  volumes:
    - ./log:/app/log
    - ./data/storage:/app/storage
  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure
  depends_on:
    - mysql

services:
  nginx:
    image: ${IMAGE_FRONTEND}
    platform: linux/amd64
    env_file:
      - ./secrets/.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx-server.conf:/etc/nginx/conf.d/default.conf
      - ./secrets/ssl.crt:/etc/nginx/ssl.crt
      - ./secrets/ssl.key:/etc/nginx/ssl.key
    depends_on:
      - rails # nginx server 配置中用了 host，因此需要先启动 service
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  rails:
    <<: *app
    command: bash -c "bin/rails db:migrate db:seed && rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
  mysql:
    image: ${IMAGE_PROXY:-}mysql:8.0
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai
      MYSQL_DATABASE: admin_template_production
    volumes:
      - prod_mysql:/var/lib/mysql

volumes:
  prod_mysql:
